### ISSUE TITLE
Issue with membrane rtsp after v0.7.2

### ISSUE THREAD

**Issue by gBillal** [membraneframework/membrane_core#863]
Since [v0.7.2](https://github.com/membraneframework/membrane_rtsp/pull/42) where the tcp socket is set to active mode. This causes issues when someone want full control of the underlying tcp socket. 

In my case I get the socket and set `active` to false, so once I try to `:gen_tcp.recv` and the socket try to send a message in another process, I get the error `{:error, :einval}` (because the socket is set to active mode)

**Comment by Noarkhh** [comment]
Hi, I see the issue. In https://github.com/membraneframework/membrane_rtsp/pull/44 the behavior changes (after transferring control the session no longer tries to receive from that socket). Will it be okay if it's fixed there?

**Comment by gBillal** [comment]
That's great, I'll wait for `0.10.0` release

**Comment by Noarkhh** [comment]
I just released v0.10.0, give it a try :) Also https://github.com/gBillal/membrane_rtsp_plugin/pull/12 is now ready for review

**Comment by gBillal** [comment]
unfortunately this is still not fixing my issue. The fact that the rtsp session update the active mode of the socket creates a problem. Since I have another process that always using `recv` to read from the socket which fails when the socket is in active mode.

**Comment by Noarkhh** [comment]
are you calling `RTSP.transfer_socket_control/2` before that?

**Comment by gBillal** [comment]
Made a mistake, forgot to set the socket to non-active mode.
It works fine now, thanks
